# Generated by Django 5.1.1 on 2024-09-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('working_flag', models.BooleanField()),
                ('company', models.CharField(max_length=20)),
            ],
        ),
    ]
